default_context:
  project_name: 'Contact List App'
  project_slug: 'contact-list-app'
  domain_main: 'contact-list-app.com'
  domain_staging: 'stag.contact-list-app.com'
  docker_swarm_stack_name_main: 'contact-list-app-com'
  docker_swarm_stack_name_staging: 'stag-contact-list-app-com'
  secret_key: 'qs7$p_rw#gzm953f4mq0ga31d=45j0&x3r_g+ganip0qfac54y'
  first_superuser: 'guligon90@gmail.com'
  first_superuser_password: 'superuser'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.contact-list-app.com", "https://stag.contact-list-app.com", "https://contact-list-app.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'guligon90@gmail.com'
  postgres_password: 'root'
  pgadmin_default_user: 'guligon90@gmail.com'
  pgadmin_default_user_password: 'superuser'
  traefik_constraint_tag: 'contact-list-app.com'
  traefik_constraint_tag_staging: 'stag.contact-list-app.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:superuser'
  sentry_dsn: ''
  docker_image_prefix: 'contactlist/'
  docker_image_backend: 'contactlist/backend'
  docker_image_celeryworker: 'contactlist/celeryworker'
  docker_image_frontend: 'contactlist/frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
